# 4.1 NumPy ndarray: 다차원 배열 객체

In [1]:
import numpy as np

In [2]:
data = np.random.randn(2,3)

In [3]:
data

array([[-0.36743215,  0.49213045,  0.60883147],
       [-0.85782009,  0.65786815, -2.15211377]])

In [4]:
data * 10

array([[ -3.67432148,   4.92130448,   6.08831472],
       [ -8.57820089,   6.57868152, -21.52113767]])

In [5]:
data + data

array([[-0.7348643 ,  0.9842609 ,  1.21766294],
       [-1.71564018,  1.3157363 , -4.30422753]])

In [6]:
data.shape

(2, 3)

In [7]:
data.dtype

dtype('float64')

## 4.1.1 ndarray 생성

In [8]:
data1 = [6, 7.5, 8, 0, 1]

In [9]:
arr1 = np.array(data1)

In [10]:
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [11]:
data1.shape

AttributeError: 'list' object has no attribute 'shape'

In [12]:
arr1.shape

(5,)

In [13]:
data2 = [[1,2,3,4],[5,6,7,8]]

In [14]:
arr2 = np.array(data2)

In [15]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
arr2.ndim

2

In [17]:
arr2.shape

(2, 4)

In [18]:
arr1.dtype

dtype('float64')

In [19]:
arr2.dtype

dtype('int32')

In [20]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [21]:
np.zeros((3,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [22]:
np.empty((2,3,2))

array([[[  1.59172445e-312,   0.00000000e+000],
        [  1.41537862e+161,   5.22182633e+180],
        [  7.33952596e+223,   4.27255707e+180]],

       [[  7.04850274e-120,   4.90900659e+252],
        [  3.88621453e+285,   2.91237123e+257],
        [  4.71294503e+257,   2.60096959e-306]]])

In [23]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## 4.1.2 ndarray의 자료형

In [24]:
arr1 = np.array([1,2,3], dtype = np.float64)

In [25]:
arr1

array([ 1.,  2.,  3.])

In [26]:
arr1.dtype

dtype('float64')

In [27]:
arr2 = np.array([1,2,3], dtype = np.int32)

In [28]:
arr2.dtype

dtype('int32')

In [29]:
arr = np.array([1,2,3,4,5])

In [30]:
arr.dtype

dtype('int32')

In [31]:
float_arr = arr.astype(np.float64)

In [32]:
float_arr.dtype

dtype('float64')

## 4.1.3 배열과 스칼라 간의 연산

In [33]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])

In [34]:
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [35]:
arr * arr

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [36]:
arr - arr

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [37]:
1 / arr

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [38]:
arr ** 5

array([[  1.00000000e+00,   3.20000000e+01,   2.43000000e+02],
       [  1.02400000e+03,   3.12500000e+03,   7.77600000e+03]])

## 4.1.4 색인과 슬라이싱 기초

In [39]:
arr = np.arange(10)

In [40]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
arr[5]

5

In [42]:
arr[5:8]

array([5, 6, 7])

In [43]:
arr[5:8] = 12

In [44]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [45]:
arr_slice = arr[5:8]

In [46]:
arr_slice[1]

12

In [47]:
arr_slice[1] = 12345

In [48]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,     9])

In [49]:
arr_slice[:] = 64

In [50]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [51]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [52]:
arr2d[2]

array([7, 8, 9])

In [53]:
arr2d[0][2]

3

In [54]:
arr2d[0,2]

3

In [55]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [56]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [57]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
old_alues = arr3d[0].copy()

In [59]:
arr3d[0]=42

In [60]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [61]:
arr3d[0] = old_alues

In [62]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [63]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [66]:
arr2d[1, :2]

array([4, 5])

In [67]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

## 4.1.5 불리언 색인

In [68]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [69]:
data = np.random.randn(7,4)

In [70]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'],
      dtype='<U4')

In [71]:
data

array([[-2.06776012, -0.71597194, -0.94430167, -1.35039106],
       [-0.60607108, -0.28762161,  0.30537695,  0.4504203 ],
       [ 0.78286751,  0.41901369,  0.06937923,  0.76998928],
       [-1.63204718,  0.48189104,  0.79787012,  0.33299278],
       [ 0.20747052,  0.8104942 ,  0.09660669, -0.34826733],
       [-0.34709386,  0.52775532,  0.51988797, -0.6655919 ],
       [ 0.37076148, -0.91049957, -0.79112305,  0.72402149]])

In [72]:
names == 'Bob'

array([ True, False, False,  True, False, False, False], dtype=bool)

In [73]:
data[names == 'Bob']

array([[-2.06776012, -0.71597194, -0.94430167, -1.35039106],
       [-1.63204718,  0.48189104,  0.79787012,  0.33299278]])

In [74]:
data[names == 'Bob', 2:]

array([[-0.94430167, -1.35039106],
       [ 0.79787012,  0.33299278]])

In [75]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True], dtype=bool)

In [76]:
data[~(names == 'Bob')]

array([[-0.60607108, -0.28762161,  0.30537695,  0.4504203 ],
       [ 0.78286751,  0.41901369,  0.06937923,  0.76998928],
       [ 0.20747052,  0.8104942 ,  0.09660669, -0.34826733],
       [-0.34709386,  0.52775532,  0.51988797, -0.6655919 ],
       [ 0.37076148, -0.91049957, -0.79112305,  0.72402149]])

In [77]:
mask = (names == 'Bob') | (names == 'Will')

In [78]:
mask

array([ True, False,  True,  True,  True, False, False], dtype=bool)

In [79]:
data[mask]

array([[-2.06776012, -0.71597194, -0.94430167, -1.35039106],
       [ 0.78286751,  0.41901369,  0.06937923,  0.76998928],
       [-1.63204718,  0.48189104,  0.79787012,  0.33299278],
       [ 0.20747052,  0.8104942 ,  0.09660669, -0.34826733]])

In [80]:
data[names != 'Joe'] = 7

In [81]:
data

array([[ 7.        ,  7.        ,  7.        ,  7.        ],
       [-0.60607108, -0.28762161,  0.30537695,  0.4504203 ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [-0.34709386,  0.52775532,  0.51988797, -0.6655919 ],
       [ 0.37076148, -0.91049957, -0.79112305,  0.72402149]])

## 4.1.6 팬시 색인

In [82]:
arr = np.empty((8,4))

In [83]:
for i in range(8):
    arr[i] = i

In [84]:
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [85]:
arr[[4,3,0,6]]

array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.],
       [ 6.,  6.,  6.,  6.]])

In [86]:
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [87]:
arr[[-3,-5,-7]]

array([[ 5.,  5.,  5.,  5.],
       [ 3.,  3.,  3.,  3.],
       [ 1.,  1.,  1.,  1.]])

In [88]:
arr = np.arange(32).reshape((8,4))

In [89]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [90]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [91]:
arr[1]

array([4, 5, 6, 7])

In [92]:
arr[[1,5,7,2]][:,[0,3,1,3]]

array([[ 4,  7,  5,  7],
       [20, 23, 21, 23],
       [28, 31, 29, 31],
       [ 8, 11,  9, 11]])

In [93]:
arr[[1,5,7,2]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

## 4.1.7 배열 전치와 축 바꾸기

In [94]:
arr = np.arange(15).reshape(3,5)

In [95]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [96]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [97]:
arr = np.random.randn(6,3)

In [98]:
np.dot(arr.T, arr)

array([[ 6.64877756,  2.06221189,  2.25430643],
       [ 2.06221189,  5.05829674, -1.59939389],
       [ 2.25430643, -1.59939389,  3.33368995]])

In [99]:
arr = np.arange(16).reshape(2,2,4)

In [100]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [101]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [102]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [103]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])